name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter (STABLE LOCKED)
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          version: 3.22.3

      - name: Clean project
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Generate Hive adapters
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: seeking-apk
          path: build/app/outputs/flutter-apk/app-release.apk